apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sylo-toolkit-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: toolkit-loader
spec:
  template:
    spec:
      containers:
      - name: loader
        image: debian:buster-slim
        command: ["/bin/bash", "-c"]
        args:
          - |
            set -e
            echo "Pointing to Debian Archive (Buster)..."
            echo "deb http://archive.debian.org/debian buster main contrib non-free" > /etc/apt/sources.list
            echo "deb http://archive.debian.org/debian-security buster/updates main contrib non-free" >> /etc/apt/sources.list
            
            echo "Installing tools..."
            apt-get -o Acquire::Check-Valid-Until=false update
            apt-get install -y --allow-unauthenticated curl git htop vim netcat-openbsd python3 tmux file
            
            echo "Cleaning corrupt files on Host..."
            rm -f /host/bin/htop /host/bin/curl /host/bin/git /host/bin/vim /host/bin/nc /host/bin/tmux /host/bin/python3
            
            echo "Injecting fresh binaries (Buster/Glibc-2.28)..."
            cp -f /usr/bin/htop /host/bin/
            cp -f /usr/bin/curl /host/bin/
            cp -f /usr/bin/git /host/bin/
            cp -f /usr/bin/vim /host/bin/
            
            if [ -f /bin/nc.openbsd ]; then cp -f /bin/nc.openbsd /host/bin/nc; 
            elif [ -f /usr/bin/nc ]; then cp -f /usr/bin/nc /host/bin/; fi
            
            cp -f /usr/bin/tmux /host/bin/
            cp -f /usr/bin/python3 /host/bin/
            
            echo "Verifying injection..."
            ls -l /host/bin/htop
            file /host/bin/htop
            
            chmod +x /host/bin/* 2>/dev/null
            echo "Toolkit Ready (Archive Edition)."
        volumeMounts:
        - name: toolkit-vol
          mountPath: /mnt/toolkit
        - name: host-bin
          mountPath: /host/bin

      restartPolicy: OnFailure
      volumes:
      - name: toolkit-vol
        persistentVolumeClaim:
          claimName: sylo-toolkit-pvc
      - name: host-bin
        hostPath:
          path: /usr/local/bin
          type: Directory
